CREATE TABLE USERS(
[ID_USER] int primary key identity(1,1),
[LOGIN] NVARCHAR(50),
[NAME] NVARCHAR(100),
[EMAIL] NVARCHAR(100),
[PASSWORD] NVARCHAR(255)
)

CREATE TABLE HOTELS(
[ID_HOTEL] INT PRIMARY KEY IDENTITY(1,1),
[PLACE_ID] NVARCHAR(255),
[NAME] NVARCHAR(255),
[FULLADDRESS] NVARCHAR(500),
[WEBPAGE] NVARCHAR(200),
[LAT] NVARCHAR(20),
[LNG] NVARCHAR(20),
[DESCRIPTION] NVARCHAR(max),
[RATE] INT,
[GOOGLE_RATE] FLOAT,
[STREET_NUM] INT,
[STREET] NVARCHAR(200),
[CITY] NVARCHAR(200),
[COUNTRY] NVARCHAR(100),
[POSTCODE] NVARCHAR(6),
[PHONE] NVARCHAR(30)
)

CREATE TABLE OFFERS
(
[ID_OFFER] INT PRIMARY KEY IDENTITY(1,1),
[ID_HOTEL] INT,
[NAME] NVARCHAR(255),
[DESCRIPTION] NVARCHAR(MAX),
[DATE_START] DATE,
[DATE_END] DATE,
[PRICE] FLOAT,
FOREIGN KEY (ID_HOTEL) REFERENCES HOTELS(ID_HOTEL)
)

CREATE TABLE HOTEL_RATES(
[ID_HOTEL] INT,
[ID_USER] INT,
[RATE] INT
PRIMARY KEY (ID_HOTEL, ID_USER),
FOREIGN KEY (ID_HOTEL) REFERENCES HOTELS(ID_HOTEL),
FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
)


